### ISSUE TITLE
Working with Conda

### ISSUE THREAD

**Issue by joaogui1** [jktr/matplotlib-backend-kitty#2]
Since I'm using conda I don't have a set `PYTHONPATH`, can you help me out? I tried using [conda develop](https://docs.conda.io/projects/conda-build/en/latest/resources/commands/conda-develop.html) and pointing to the repo, but despite it being added to the path.
Output of `python -c "import sys; print(sys.path)"`                              
```
['', '/home/joaogui/miniconda3/lib/python37.zip', '/home/joaogui/miniconda3/lib/python3.7', '/home/joaogui/miniconda3/lib/python3.7/lib-dynload', '/home/joaogui/miniconda3/lib/python3.7/site-packages', '/home/joaogui/Downloads/matplotlib-backend-kitty']
```

**Comment by wardw** [comment]
I've not used Conda, but I suspect the path you want to set is to the folder containing your `matplotlib-backend-kitty` folder.  In your case that would just be `/home/joaogui/Downloads/`.

**Comment by jktr** [comment]
I don't use conda either, so I'm not sure if there's a recommended way to do this.

Adding `/home/joaogui/miniconda3/lib/python3.7/site-packages` to `sys.path` probably does not work as [PYTHONPATH](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) expects a list of directories containing packages instead of a list of packages.

You already seem to have a `site-packages` directory for conda at  `/home/joaogui/miniconda3/lib/python3.7/site-packages`. I'd expect that cloning this repository to that directory would allow conda's python to pick it up.

If this works for you, I'll probably amend the readme to this effect.

**Comment by alonsoC1s** [comment]
Hello. I was having the same issue and I managed to solve it by cloning this repo into `~/user/miniconda3/envs/myenv/lib/python3.9/site-packages/IPython/extensions`, where `myenv` is the name of the env I installed it to. Maybe it could be possible to makea package that does exactly this and publish it to conda-forge?

**Comment by jktr** [comment]
I've tried clarifying the usage of `PYTHONPATH` and `site-packages` directories in the readme.

I don't currently plan to publish packages for this in the pip or conda repositories.
