### ISSUE TITLE
Control the image size being showed in kitty?

### ISSUE THREAD

**Issue by h4pZ** [jktr/matplotlib-backend-kitty#3]
Hi, I was wondering if there is a way to control the size of the plot being shown on the terminal, since it always takes the whole terminal window no matter the figsize

**Comment by jktr** [comment]
Plot size isn't configurable at the moment.

The plot's backing figure is actually resized on draw to match the
terminal's current size. This is so that making your terminal larger
takes advantage of the additional space and making your terminal smaller
doesn't cut off parts of any subsequently rendered figure.

Could you describe your usecase for wanting differently-sized plots?

**Comment by h4pZ** [comment]
By getting different sized plots you could have a similar experience as in a jupyter notebook / lab., which was something I'm familiar with.

Also, sometimes I'll have two terminals, one with nvim and the other one with ipython. I'll iterate over my code by writing something on nvim and the executing it on ipython with something like vim-slime. In case of working with plots, being able to see how the actual image would look like when saved can help in this loop.

The last thing I can think of is when I have only ipython open, plotting it in the terminal doesn't allow me to see the previous code blocks I've written which is a little bit of an annoyance .

![](https://i.imgur.com/sNq8L5z.png)

**Comment by jktr** [comment]
You can now set the environment variable `MPLBACKEND_KITTY_SIZING` to `manual` to disable the automatic resizing.
